import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/componant/header";
import Footer from "@/app/componant/footer";
import {NextWrapper} from "@/app/Session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-[100%] relative">
      <body className={inter.className}>
      <NextWrapper>
      <Header/>



      <div className="lg:m-10 m-2">{children}</div>

      <div className="">
      <Footer/>
      </div>
      </NextWrapper>
      </body>
    </html>
  );
}
